### ISSUE TITLE
Doesn't work with trezorlib 0.12.0 (tested on Ubuntu 20.04 beta)

### ISSUE THREAD

**Issue by marza91** [romanz/trezor-agent#319]
This is probably my fault for testing a beta version of 20.04, but I thought it could be worth posting this here. When running any command where trezor-agent tries to contact the trezor-device, I get the error trace pasted below. I've tried multiple ways of installing Cython, hidapi and trezor_agent, but I seem to end up on the same result. Tried at first with "pip3 install", but due to another warning it urged me to use "python3 -m pip" instead, so I tried that as well, with and without the --user flag, and as root (without --user). Interestingly I'm getting a similar error now from "ssh-add -l", so I'm not sure if this is an underlying issue, or ssh-add trying to talk to the trezor-agent. I've successfully installed trezor-bridge which is running, and I can open my device using the browser software at wallet.trezor.io. Currently all three pip packages are installed under $HOME/.local/bin, and I've also installed the mentioned dependencies from the install guide. Anything I'm missing, or is it probably because I'm running an unstable beta?

Python version: 3.8.2
Pip version: 20.0.2

```
Traceback (most recent call last):
  File "/home/marza91/.local/bin/trezor-agent", line 8, in <module>
    sys.exit(ssh_agent())
  File "/home/marza91/.local/bin/trezor_agent.py", line 5, in <lambda>
    ssh_agent = lambda: libagent.ssh.main(DeviceType)
  File "/usr/local/lib/python3.8/dist-packages/libagent/ssh/__init__.py", line 174, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/libagent/ssh/__init__.py", line 311, in main
    for pk in conn.public_keys():
  File "/usr/local/lib/python3.8/dist-packages/libagent/ssh/__init__.py", line 210, in public_keys
    self.public_keys_cache = conn.export_public_keys(self.identities)
  File "/usr/local/lib/python3.8/dist-packages/libagent/ssh/client.py", line 24, in export_public_keys
    with self.device:
  File "/usr/local/lib/python3.8/dist-packages/libagent/device/interface.py", line 126, in __enter__
    self.conn = self.connect()
  File "/usr/local/lib/python3.8/dist-packages/libagent/device/trezor.py", line 55, in connect
    connection = self._defs.Client(transport=transport,
TypeError: __init__() got an unexpected keyword argument 'state'

```

**Comment by marza91** [comment]
Did some digging and found this change in trezorlib:
https://github.com/trezor/trezor-firmware/commit/90d5cdfd5be242f04a87a0576d762710b9e8d213#diff-2e961b6b5d84421cb7dc376e57a569deL114

Seems like they removed the "state" variable and replaced it with "session_id". I'll try to see if it's enough to just change the variable name or if more changes are needed to fix it.

**Comment by marza91** [comment]
This is indeed the new 0.12.0 release of trezorlib causing issues. Got it working by manually downgrading as a temp workaround:

```
sudo python -m pip uninstall trezor
python -m pip install --user trezor==0.11.6
```

replace sudo, --user and -m pip(3) as desired.

Going to see if I can get the git version of trezor-agent up and running, and then see if I can make it work with trezorlib 0.12.0

**Comment by marza91** [comment]
Didn't have much luck with this so far, most of the day went by setting up a new machine (the one with 20.04, but I might be able to look more into it later next week unless someone else does.

**Comment by SimonVrouwe** [comment]
Coincidentally I encountered the same issue yesterday on a Debian 10 and an Ubuntu 19 machine, which is frustrating.

Downgrading to older versions of `trezor` and `trezor-agent` solves it.
```
pip3 uninstall trezor_agent trezor
pip3 install trezor==0.11.6
pip3 install trezor_agent==0.9.3
 ```

**Comment by marza91** [comment]
@SimonVrouwe 
Are you sure you need to downgrade trezor_agent? It works fine on my machine by only downgrading the `trezor` package.

**Comment by prusnak** [comment]
We changed the API in 0.12

trezor-agent should require python-trezorlib >= 0.11 < 0.12

After the fix is applied we could change this to >= 0.12 < 0.13
